<?php

namespace Database\Seeders;

use App\Models\ServiceCategory;
use App\Models\SubServiceCategory;
use Illuminate\Database\Seeder;

class SubServiceCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'service_name' => 'Maintenance',
                'short_title' => 'Routine Care',
                'status' => 1,
                'meta_title' => 'Vehicle Maintenance Services',
                'meta_keywords' => 'maintenance, oil change, tune up, fluid service',
                'meta_description' => 'Keep your vehicle reliable with routine maintenance and fluid services.',
            ],
            [
                'service_name' => 'Diagnostics',
                'short_title' => 'Problem Finding',
                'status' => 1,
                'meta_title' => 'Auto Diagnostics Services',
                'meta_keywords' => 'diagnostics, engine scan, inspection, checkup',
                'meta_description' => 'Accurate diagnostics that identify issues before they become repairs.',
            ],
            [
                'service_name' => 'Repair',
                'short_title' => 'Fix and Restore',
                'status' => 1,
                'meta_title' => 'Auto Repair Services',
                'meta_keywords' => 'auto repair, brake repair, transmission, suspension',
                'meta_description' => 'Trusted repairs for safety, performance, and long-term value.',
            ],
            [
                'service_name' => 'Detailing',
                'short_title' => 'Clean and Protect',
                'status' => 1,
                'meta_title' => 'Car Detailing Services',
                'meta_keywords' => 'detailing, paint correction, ceramic coating, interior',
                'meta_description' => 'Professional detailing that restores shine and protects your finish.',
            ],
            [
                'service_name' => 'Tires and Wheels',
                'short_title' => 'Grip and Control',
                'status' => 1,
                'meta_title' => 'Tire and Wheel Services',
                'meta_keywords' => 'tires, wheel alignment, rotation, balancing',
                'meta_description' => 'Tire and wheel services for comfort, control, and safety.',
            ],
        ];

        $categoryIdByName = [];
        foreach ($categories as $category) {
            $model = ServiceCategory::firstOrCreate(
                ['service_name' => $category['service_name']],
                $category
            );
            $categoryIdByName[$model->service_name] = $model->id;
        }

        $services = [
            [
                'category' => 'Maintenance',
                'sub_service_name' => 'Oil Change Service',
                'banner_short_title' => 'Fresh oil, smoother drive',
                'banner_long_title' => 'Oil Change Service for Clean Engine Performance',
                'banner_description' => 'Protect your engine with the right oil and a quality filter at every interval.',
                'service_introduction_description' => $this->buildIntroduction('Oil Change Service', 'Maintenance'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>OEM grade oil and filter</li><li>Fluid top-up check</li><li>Maintenance sticker reminder</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Quieter operation</li><li>Better mileage</li><li>Longer engine life</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Confirm oil spec</li><li>Drain, replace, and refill</li><li>Quick inspection</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Cleaner engine oil</li><li>Stable engine temperature</li><li>Reliable startup</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Oil Change Service | Clean Engine Performance',
                'meta_keywords' => 'oil change, engine oil, oil filter, maintenance',
                'meta_description' => 'Fast and reliable oil change service for smooth, efficient driving.',
            ],
            [
                'category' => 'Maintenance',
                'sub_service_name' => 'Fluid Flush and Top-Up',
                'banner_short_title' => 'Fluids that protect',
                'banner_long_title' => 'Fluid Flush and Top-Up Service',
                'banner_description' => 'Refresh critical fluids to protect components and prevent wear.',
                'service_introduction_description' => $this->buildIntroduction('Fluid Flush and Top-Up', 'Maintenance'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Coolant, brake, and power steering checks</li><li>Fluid condition testing</li><li>Safe disposal and refill</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Improved system response</li><li>Reduced corrosion risk</li><li>Consistent performance</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect fluid condition</li><li>Flush if needed</li><li>Refill to spec</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Stable operating temps</li><li>Reliable braking feel</li><li>Longer component life</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Fluid Flush Service | Protect Critical Systems',
                'meta_keywords' => 'fluid flush, coolant, brake fluid, maintenance',
                'meta_description' => 'Full fluid inspection and flush to protect your vehicle systems.',
            ],
            [
                'category' => 'Maintenance',
                'sub_service_name' => 'Tune-Up Service',
                'banner_short_title' => 'Restore performance',
                'banner_long_title' => 'Tune-Up Service for Smooth Power',
                'banner_description' => 'Improve throttle response and fuel efficiency with a complete tune-up.',
                'service_introduction_description' => $this->buildIntroduction('Tune-Up Service', 'Maintenance'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Spark plug inspection</li><li>Air and fuel filter check</li><li>Idle and timing scan</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Better acceleration</li><li>Lower emissions</li><li>Improved mileage</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Scan for codes</li><li>Replace worn items</li><li>Verify performance</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Smoother idle</li><li>Consistent power</li><li>Reliable starts</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Tune-Up Service | Restore Engine Performance',
                'meta_keywords' => 'tune up, spark plugs, performance, maintenance',
                'meta_description' => 'Comprehensive tune-up service to bring back smooth power and mileage.',
            ],
            [
                'category' => 'Maintenance',
                'sub_service_name' => 'Battery Replacement',
                'banner_short_title' => 'Confident starts',
                'banner_long_title' => 'Battery Replacement and Testing',
                'banner_description' => 'Stay ready with reliable battery testing and replacement.',
                'service_introduction_description' => $this->buildIntroduction('Battery Replacement', 'Maintenance'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Battery load test</li><li>Terminal cleaning</li><li>Correct fit and install</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Fast starts</li><li>Reliable power delivery</li><li>Longer battery life</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Test battery health</li><li>Confirm size and rating</li><li>Install and verify</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Strong cranking power</li><li>Stable electrical system</li><li>Peace of mind</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Car Battery Replacement | Reliable Starts',
                'meta_keywords' => 'battery replacement, battery test, car battery',
                'meta_description' => 'Battery testing and replacement for dependable starting power.',
            ],
            [
                'category' => 'Diagnostics',
                'sub_service_name' => 'Engine Diagnostics',
                'banner_short_title' => 'Find issues fast',
                'banner_long_title' => 'Engine Diagnostics for Accurate Repairs',
                'banner_description' => 'Pinpoint engine issues with advanced scanning and testing.',
                'service_introduction_description' => $this->buildIntroduction('Engine Diagnostics', 'Diagnostics'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>OBD scan and live data</li><li>Compression checks</li><li>Sensor verification</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Accurate diagnosis</li><li>Fewer repeat visits</li><li>Cost control</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Scan and test</li><li>Inspect key systems</li><li>Share clear findings</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Clear repair plan</li><li>Resolved warning lights</li><li>Improved performance</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Engine Diagnostics | Accurate Auto Testing',
                'meta_keywords' => 'engine diagnostics, check engine light, scan tool',
                'meta_description' => 'Advanced diagnostics to identify engine issues with confidence.',
            ],
            [
                'category' => 'Diagnostics',
                'sub_service_name' => 'Brake Inspection',
                'banner_short_title' => 'Safe stops',
                'banner_long_title' => 'Brake Inspection for Safety and Control',
                'banner_description' => 'Detailed brake inspection to keep stopping power strong.',
                'service_introduction_description' => $this->buildIntroduction('Brake Inspection', 'Diagnostics'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Pad and rotor measurement</li><li>Fluid condition check</li><li>Hardware inspection</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Shorter stopping distance</li><li>Early wear detection</li><li>Peace of mind</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect all corners</li><li>Measure wear</li><li>Report findings</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Clear wear report</li><li>Safer braking</li><li>Reduced noise</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Brake Inspection | Safer Stopping Power',
                'meta_keywords' => 'brake inspection, pads, rotors, safety',
                'meta_description' => 'Comprehensive brake inspection to ensure safe stopping.',
            ],
            [
                'category' => 'Diagnostics',
                'sub_service_name' => 'AC System Diagnostics',
                'banner_short_title' => 'Cool and comfortable',
                'banner_long_title' => 'AC Diagnostics for Reliable Cooling',
                'banner_description' => 'We find leaks and performance issues to restore cold air.',
                'service_introduction_description' => $this->buildIntroduction('AC System Diagnostics', 'Diagnostics'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Pressure and leak testing</li><li>Cabin airflow check</li><li>Compressor evaluation</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Faster cooling</li><li>Reduced odor</li><li>Improved comfort</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect and test</li><li>Verify airflow</li><li>Recommend repair</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Stable cabin temperature</li><li>Clear service plan</li><li>Improved efficiency</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'AC Diagnostics | Restore Cold Air',
                'meta_keywords' => 'ac diagnostics, car ac, refrigerant, cooling',
                'meta_description' => 'AC diagnostics to restore reliable cooling and airflow.',
            ],
            [
                'category' => 'Diagnostics',
                'sub_service_name' => 'Pre-Purchase Inspection',
                'banner_short_title' => 'Buy with confidence',
                'banner_long_title' => 'Pre-Purchase Vehicle Inspection',
                'banner_description' => 'Know the real condition of a vehicle before you buy.',
                'service_introduction_description' => $this->buildIntroduction('Pre-Purchase Inspection', 'Diagnostics'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Road test and scan</li><li>Undercarriage review</li><li>Fluid and leak check</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Reduce purchase risk</li><li>Know repair needs</li><li>Negotiation leverage</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect, scan, and test</li><li>Document findings</li><li>Explain next steps</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Clear condition report</li><li>Smarter purchase decision</li><li>Budget planning</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Pre-Purchase Inspection | Buy Smarter',
                'meta_keywords' => 'pre purchase inspection, used car check, vehicle inspection',
                'meta_description' => 'Full vehicle inspection before purchase for clear, honest insight.',
            ],
            [
                'category' => 'Repair',
                'sub_service_name' => 'Brake Repair',
                'banner_short_title' => 'Stop with confidence',
                'banner_long_title' => 'Brake Repair for Safe Driving',
                'banner_description' => 'Restore braking power with quality parts and expert service.',
                'service_introduction_description' => $this->buildIntroduction('Brake Repair', 'Repair'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Pad and rotor replacement</li><li>Caliper service</li><li>Brake fluid bleed</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Quiet braking</li><li>Improved safety</li><li>Better pedal feel</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect and confirm</li><li>Replace worn parts</li><li>Road test</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Shorter stopping distance</li><li>No vibration</li><li>Consistent response</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Brake Repair | Quiet and Safe Stops',
                'meta_keywords' => 'brake repair, pads, rotors, calipers',
                'meta_description' => 'Complete brake repair for safe stopping and smooth pedal feel.',
            ],
            [
                'category' => 'Repair',
                'sub_service_name' => 'Transmission Service',
                'banner_short_title' => 'Shift smooth again',
                'banner_long_title' => 'Transmission Service and Care',
                'banner_description' => 'Protect your transmission with proper service and inspection.',
                'service_introduction_description' => $this->buildIntroduction('Transmission Service', 'Repair'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Fluid change or flush</li><li>Pan and gasket inspection</li><li>Shift quality check</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Smoother shifting</li><li>Reduced heat</li><li>Longer transmission life</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Check fluid condition</li><li>Service to spec</li><li>Verify operation</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Consistent shifting</li><li>Lower noise</li><li>Improved reliability</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Transmission Service | Smooth Shifting',
                'meta_keywords' => 'transmission service, transmission fluid, shift repair',
                'meta_description' => 'Transmission service to improve shifting and protect your drivetrain.',
            ],
            [
                'category' => 'Repair',
                'sub_service_name' => 'Suspension Repair',
                'banner_short_title' => 'Stable ride',
                'banner_long_title' => 'Suspension Repair for Better Handling',
                'banner_description' => 'Fix clunks, uneven wear, and poor handling with suspension repair.',
                'service_introduction_description' => $this->buildIntroduction('Suspension Repair', 'Repair'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Shock and strut replacement</li><li>Bushing inspection</li><li>Steering component check</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Improved control</li><li>Smoother ride</li><li>Even tire wear</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect suspension</li><li>Replace worn parts</li><li>Verify alignment</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Better handling</li><li>Reduced noise</li><li>Comfortable ride</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Suspension Repair | Smooth and Stable Ride',
                'meta_keywords' => 'suspension repair, shocks, struts, handling',
                'meta_description' => 'Suspension repair that restores control, comfort, and safety.',
            ],
            [
                'category' => 'Repair',
                'sub_service_name' => 'Radiator Repair',
                'banner_short_title' => 'Keep it cool',
                'banner_long_title' => 'Radiator Repair and Cooling Service',
                'banner_description' => 'Prevent overheating with radiator repair and cooling system care.',
                'service_introduction_description' => $this->buildIntroduction('Radiator Repair', 'Repair'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Leak detection</li><li>Hose and clamp replacement</li><li>Cooling system pressure test</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Stable temperature</li><li>Reduced engine stress</li><li>Reliable operation</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect and test</li><li>Repair or replace</li><li>Verify cooling</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>No coolant leaks</li><li>Lower overheating risk</li><li>Better efficiency</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Radiator Repair | Prevent Overheating',
                'meta_keywords' => 'radiator repair, cooling system, coolant leak',
                'meta_description' => 'Radiator repair and cooling system service to prevent overheating.',
            ],
            [
                'category' => 'Detailing',
                'sub_service_name' => 'Interior Detailing',
                'banner_short_title' => 'Fresh inside',
                'banner_long_title' => 'Interior Detailing for a Clean Cabin',
                'banner_description' => 'Deep clean and protect every surface inside your vehicle.',
                'service_introduction_description' => $this->buildIntroduction('Interior Detailing', 'Detailing'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Vacuum and steam cleaning</li><li>Stain removal</li><li>Plastic and leather care</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Cleaner air</li><li>Odor reduction</li><li>Like-new look</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Prepare and protect</li><li>Deep clean surfaces</li><li>Condition and finish</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Fresh appearance</li><li>Sanitized cabin</li><li>Longer interior life</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Interior Detailing | Fresh and Clean Cabin',
                'meta_keywords' => 'interior detailing, car cleaning, upholstery',
                'meta_description' => 'Interior detailing for a clean, fresh, and protected cabin.',
            ],
            [
                'category' => 'Detailing',
                'sub_service_name' => 'Paint Correction',
                'banner_short_title' => 'Bring back shine',
                'banner_long_title' => 'Paint Correction for Deep Gloss',
                'banner_description' => 'Remove swirls and haze for a mirror-like finish.',
                'service_introduction_description' => $this->buildIntroduction('Paint Correction', 'Detailing'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Paint inspection</li><li>Machine polishing</li><li>Finishing protection</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Glossy finish</li><li>Reduced swirls</li><li>Improved resale value</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Measure paint condition</li><li>Correct and refine</li><li>Protect the finish</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Clear, deep shine</li><li>Uniform reflections</li><li>Protected paint</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Paint Correction | Restore Deep Gloss',
                'meta_keywords' => 'paint correction, polishing, swirl removal',
                'meta_description' => 'Paint correction service to remove swirls and restore deep gloss.',
            ],
            [
                'category' => 'Detailing',
                'sub_service_name' => 'Ceramic Coating',
                'banner_short_title' => 'Long-lasting protection',
                'banner_long_title' => 'Ceramic Coating for Durable Shine',
                'banner_description' => 'Shield your paint with long-term hydrophobic protection.',
                'service_introduction_description' => $this->buildIntroduction('Ceramic Coating', 'Detailing'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Surface prep and polish</li><li>Professional coating application</li><li>Final cure and inspection</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Easy washing</li><li>Deep gloss</li><li>UV protection</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Prepare paint</li><li>Apply coating</li><li>Verify finish</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Durable protection</li><li>Water beading</li><li>Showroom shine</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Ceramic Coating | Durable Paint Protection',
                'meta_keywords' => 'ceramic coating, paint protection, detailing',
                'meta_description' => 'Ceramic coating for long-lasting protection and glossy finish.',
            ],
            [
                'category' => 'Detailing',
                'sub_service_name' => 'Headlight Restoration',
                'banner_short_title' => 'Clear night vision',
                'banner_long_title' => 'Headlight Restoration for Safer Driving',
                'banner_description' => 'Remove haze and improve visibility with headlight restoration.',
                'service_introduction_description' => $this->buildIntroduction('Headlight Restoration', 'Detailing'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Lens sanding and polish</li><li>UV protective seal</li><li>Brightness check</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Improved visibility</li><li>Better appearance</li><li>Longer lens life</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Clean and prep</li><li>Restore clarity</li><li>Seal and protect</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Clear lenses</li><li>Brighter lights</li><li>Safer night driving</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Headlight Restoration | Clear and Bright',
                'meta_keywords' => 'headlight restoration, lens polish, visibility',
                'meta_description' => 'Headlight restoration service for clearer lenses and safer driving.',
            ],
            [
                'category' => 'Tires and Wheels',
                'sub_service_name' => 'Tire Rotation',
                'banner_short_title' => 'Even tire wear',
                'banner_long_title' => 'Tire Rotation for Longer Tire Life',
                'banner_description' => 'Rotate tires for balanced wear and a smoother ride.',
                'service_introduction_description' => $this->buildIntroduction('Tire Rotation', 'Tires and Wheels'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Front to rear rotation</li><li>Tread depth check</li><li>Pressure adjustment</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Even tread wear</li><li>Better traction</li><li>Longer tire life</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Inspect tires</li><li>Rotate pattern</li><li>Set pressure</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Balanced wear</li><li>Quieter ride</li><li>Improved handling</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Tire Rotation | Extend Tread Life',
                'meta_keywords' => 'tire rotation, tire wear, maintenance',
                'meta_description' => 'Tire rotation service to extend tread life and improve handling.',
            ],
            [
                'category' => 'Tires and Wheels',
                'sub_service_name' => 'Wheel Alignment',
                'banner_short_title' => 'Drive straight',
                'banner_long_title' => 'Wheel Alignment for Smooth Tracking',
                'banner_description' => 'Correct alignment to protect tires and improve steering.',
                'service_introduction_description' => $this->buildIntroduction('Wheel Alignment', 'Tires and Wheels'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Camber, caster, toe adjustment</li><li>Steering angle check</li><li>Before and after readings</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Reduced tire wear</li><li>Better fuel economy</li><li>Improved stability</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Measure alignment</li><li>Adjust to spec</li><li>Test drive</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Straight steering</li><li>Even tire wear</li><li>Confident handling</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Wheel Alignment | Protect Your Tires',
                'meta_keywords' => 'wheel alignment, camber, toe, handling',
                'meta_description' => 'Precision alignment service to improve handling and tire life.',
            ],
            [
                'category' => 'Tires and Wheels',
                'sub_service_name' => 'Tire Replacement',
                'banner_short_title' => 'New grip, safer miles',
                'banner_long_title' => 'Tire Replacement and Fitment',
                'banner_description' => 'Get the right tires installed for safety, comfort, and control.',
                'service_introduction_description' => $this->buildIntroduction('Tire Replacement', 'Tires and Wheels'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Size and load rating check</li><li>Mount and balance</li><li>Pressure and torque set</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Better traction</li><li>Quieter ride</li><li>Improved safety</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Confirm tire fitment</li><li>Install and balance</li><li>Final inspection</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Reliable grip</li><li>Smooth ride</li><li>Even wear</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Tire Replacement | Safe and Smooth Ride',
                'meta_keywords' => 'tire replacement, new tires, tire installation',
                'meta_description' => 'Professional tire replacement and fitment for safe driving.',
            ],
            [
                'category' => 'Tires and Wheels',
                'sub_service_name' => 'Rim Refinishing',
                'banner_short_title' => 'Wheels that shine',
                'banner_long_title' => 'Rim Refinishing for Like-New Wheels',
                'banner_description' => 'Restore scuffed or faded wheels with expert refinishing.',
                'service_introduction_description' => $this->buildIntroduction('Rim Refinishing', 'Tires and Wheels'),
                'key_services_list' => 'Key Services',
                'key_service_description' => '<ul><li>Surface prep and repair</li><li>Color and clear coat</li><li>Final polish</li></ul>',
                'features_and_benefit_list' => 'Features and Benefits',
                'features_and_benefit_description' => '<ul><li>Improved appearance</li><li>Corrosion protection</li><li>Higher vehicle value</li></ul>',
                'how_do_we_work_list' => 'How We Work',
                'how_do_we_work_description' => '<ul><li>Assess damage</li><li>Refinish and coat</li><li>Quality check</li></ul>',
                'expected_result_list' => 'Expected Results',
                'expected_result_description' => '<ul><li>Clean, even finish</li><li>Reduced blemishes</li><li>Fresh wheel look</li></ul>',
                'quantity' => 1,
                'svg_icon' => null,
                'status' => 1,
                'meta_title' => 'Rim Refinishing | Restore Wheel Finish',
                'meta_keywords' => 'rim refinishing, wheel repair, alloy wheels',
                'meta_description' => 'Wheel refinishing service to restore a clean, like-new look.',
            ],
        ];

        foreach ($services as $service) {
            $categoryName = $service['category'];
            $service['service_category_id'] = $categoryIdByName[$categoryName] ?? array_values($categoryIdByName)[0];
            unset($service['category']);

            SubServiceCategory::updateOrCreate(
                ['sub_service_name' => $service['sub_service_name']],
                $service
            );
        }
    }

    private function buildIntroduction(string $serviceName, string $categoryName): string
    {
        $backlink = '<a href="https://dubaionlinecarcare.com/">Dubai Online Car Care</a>';
        $imageUrl = 'https://source.unsplash.com/1600x900/?' . urlencode(strtolower($serviceName) . ',car');
        $imageTag = '<figure><img src="' . $imageUrl . '" alt="' . htmlspecialchars($serviceName, ENT_QUOTES, 'UTF-8') . '"></figure>';

        $paragraphs = [
            "Looking for a trustworthy {$serviceName} that puts quality first? Our {$categoryName} specialists focus on clear diagnostics, accurate recommendations, and steady workmanship so your vehicle stays dependable. This service page is designed to help drivers understand what is included, how results are verified, and why the details matter. For more guidance on long term care, visit {$backlink} for practical resources and service tips.",
            "Every visit starts with a careful review of your vehicle condition, your driving habits, and any recent symptoms. We then outline the scope of work in plain language, confirming parts, fluids, and time expectations before any work begins. This approach helps you avoid surprises, plan your schedule, and make informed decisions. Our team documents key findings, shares before and after notes, and answers questions so you can approve the next steps with confidence.",
            "Quality comes from consistent process. We use manufacturer aware methods, verify specifications, and apply proven techniques that protect your vehicle value. Each step is performed with attention to torque settings, fluid compatibility, and safety checks. After the work is completed, we validate performance and ensure the service meets the standards that drivers expect from a professional workshop. This careful approach reduces repeat visits and builds long term reliability.",
            "Results matter. You should expect smoother performance, better efficiency, and a more predictable driving experience. We focus on early detection, preventative care, and clear communication so you can plan maintenance instead of reacting to breakdowns. The goal is to create a service experience that feels organized, transparent, and focused on real outcomes rather than quick fixes.",
            "If you are comparing providers, look for a team that explains the work, shows the value, and stands behind the results. Our {$serviceName} process emphasizes measurable improvements, honest timelines, and practical advice you can use after you leave. This is how we help drivers maintain confidence in their vehicles and protect their investment over time.",
        ];

        $text = '<p>' . $paragraphs[0] . '</p>' . $imageTag;
        $wordCount = str_word_count(strip_tags($text));
        $index = 1;

        while ($wordCount < 420) {
            $text .= '<p>' . $paragraphs[$index % count($paragraphs)] . '</p>';
            $wordCount = str_word_count(strip_tags($text));
            $index++;
        }

        return $text;
    }
}
